apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: azurecontainerdemos/webapp-linux:v1.0.0
        ports:
        - containerPort: 8000
          name: http